#!/usr/bin/env python3
"""Build-input manifest: freeze the repo-EXTERNAL inputs and re-verify them.

Policy (A05 task book §3, reviewer ruling #1): in-repo source/scripts/patches
must be committed and clean; inputs that live OUTSIDE the repo (IDF, toolchain,
managed_components, the isolated source copy, the SDKCONFIG copy, resources)
are NOT required to be committed -- but they must be frozen by a manifest that
records origin, version and hash, and re-verified before every build.

Tree hash definition (deterministic):
    sha256( "\n".join("<sha256>  <relpath>" for every file, sorted by relpath) )
  * relpaths use "/" and are relative to the entry root
  * files are hashed raw (these trees are not git-controlled; bytes are truth)
  * excludes are recorded in the entry itself, so the digest is reproducible

Generated-path policy (CP2-SOURCE-FIX-001 part B):
  A build legitimately writes a few generated headers INTO the project source
  tree, so a replayed tree cannot be byte-immutable across a build unless those
  exact paths are excluded. `exclude_files` therefore accepts EXACT relative
  file paths only:
    * no absolute paths or drive letters, no ".." segments
    * no wildcards ( * ? [ ] ) -- a pattern must never be able to widen the
      exclusion to a directory
    * the entry must not name a directory
  Anything else is a hard error in BOTH --write and --check. The list itself is
  recorded in the manifest and COMPARED on --check, so widening it is a visible,
  fail-closed manifest change. Every excluded path's existence and sha256 is
  recorded and printed, but deliberately NOT compared: those files are expected
  to be regenerated by every build. Every OTHER file stays in the digest, so any
  change to them is still a hard failure.

Usage:
  python tools/dev/verify-build-inputs.py --manifest <path> --write
  python tools/dev/verify-build-inputs.py --manifest <path> --check
Exit status: 0 ok, 1 any mismatch/missing/error, 2 usage error.
"""

import argparse
import hashlib
import json
import os
import sys

# Directories never worth hashing: build caches and VCS metadata.
DEFAULT_EXCLUDE_DIRS = {".git", "__pycache__", ".pytest_cache"}

# Characters that would turn an exact path into a pattern.
WILDCARD_CHARS = ("*", "?", "[", "]")


def validate_exclude_files(entry_id, paths):
    """Reject anything that is not an exact relative file path.

    This is the guard that keeps `exclude_files` from silently becoming a
    directory-level exclusion.
    """
    problems = []
    for p in paths:
        if not isinstance(p, str) or not p.strip():
            problems.append("%s: exclude_files entry is not a non-empty string: %r" % (entry_id, p))
            continue
        q = p.replace("\\", "/")
        parts = [s for s in q.split("/") if s not in ("", ".")]
        if q.startswith("/") or ":" in q.split("/")[0]:
            problems.append("%s: exclude_files must be relative, got %r" % (entry_id, p))
        if ".." in parts:
            problems.append("%s: exclude_files must not contain '..': %r" % (entry_id, p))
        if any(c in q for c in WILDCARD_CHARS):
            problems.append("%s: exclude_files must be an exact path, wildcards are forbidden: %r" % (entry_id, p))
        if q.endswith("/"):
            problems.append("%s: exclude_files must name a file, not a directory: %r" % (entry_id, p))
    return problems


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def file_marker(path):
    """Content digest, with explicit markers for things that cannot be read.

    Some bundled toolchain trees contain entries Windows refuses to open as a
    regular file (e.g. `msys64/etc/mtab`, and symlink-like reparse points).
    Crashing would be wrong; silently skipping would be worse. So emit a
    deterministic marker that is recorded and reported instead.
    """
    if os.path.islink(path):
        return "SYMLINK->" + os.readlink(path)
    try:
        return sha256_file(path)
    except OSError as exc:
        return "UNREADABLE:%s" % exc.errno


def tree_hash(root, extra_exclude=(), exclude_files=()):
    """Return (digest, file_count, total_bytes, unreadable_paths, excluded_state).

    `exclude_files` entries are exact relative paths; they are removed from the
    digest and their existence/hash is reported separately instead.
    """
    exclude = set(DEFAULT_EXCLUDE_DIRS) | set(extra_exclude)
    files_ex = set(p.replace("\\", "/") for p in exclude_files)
    rows = []
    total = 0
    unreadable = []
    excluded_state = []
    for r, dirs, fs in os.walk(root):
        dirs[:] = [d for d in dirs if d not in exclude]
        for f in fs:
            full = os.path.join(r, f)
            rel = os.path.relpath(full, root).replace("\\", "/")
            mark = file_marker(full)
            if rel in files_ex:
                excluded_state.append({
                    "path": rel,
                    "exists": True,
                    "sha256": None if mark.startswith(("UNREADABLE:", "SYMLINK->")) else mark,
                    "marker": None if not mark.startswith(("UNREADABLE:", "SYMLINK->")) else mark,
                    "bytes": os.path.getsize(full),
                })
                continue
            if mark.startswith(("UNREADABLE:", "SYMLINK->")):
                unreadable.append(rel + "  [" + mark + "]")
            rows.append((rel, mark))
            try:
                total += os.path.getsize(full)
            except OSError:
                pass
    seen = set(e["path"] for e in excluded_state)
    for p in sorted(files_ex - seen):
        excluded_state.append({"path": p, "exists": False, "sha256": None,
                               "marker": None, "bytes": None})
    excluded_state.sort(key=lambda e: e["path"])
    rows.sort()
    digest = hashlib.sha256(
        "\n".join("%s  %s" % (h, p) for p, h in rows).encode()
    ).hexdigest()
    return digest, len(rows), total, unreadable, excluded_state


# ---------------------------------------------------------------------------
# The A05 build inputs. `dest` is where the entry was installed inside the
# isolated build root; `exclude` must be recorded so the digest reproduces.
# ---------------------------------------------------------------------------
INPUTS = [
    {
        "id": "idf",
        "kind": "external-tree",
        "origin": r"E:\workbuddy\esp-idf-5.5.4-ascii",
        "version": "5.5.4 (tools/cmake/version.cmake; no git metadata -> no SHA claim)",
        "used_as": "IDF_PATH",
    },
    {
        "id": "idf_tools",
        "kind": "external-tree",
        "origin": r"E:\workbuddy\claw4-idf-tools",
        "version": "cmake 3.30.2 / ninja 1.12.1 / riscv32-esp-elf esp-14.2.0_20260121 / python 3.12.14",
        "used_as": "IDF_TOOLS_PATH",
    },
    {
        "id": "managed_components",
        "kind": "external-tree-installed",
        "origin": r"E:\c\managed_components",
        "version": "82 components, per E:\\c\\dependencies.lock (sha256 90af1add...)",
        "used_as": "<isolated src>/managed_components",
        # SHORT PATH (CP2-SOURCE-FIX-001 follow-up A): the isolated tree must live
        # under a SHORT root. The long TUs here carry 379 -I flags, 212 of which
        # embed the source-root path, and the Windows CreateProcess command line
        # is capped at 32,767 chars -- see run-a05-cp2-build.ps1, header comment.
        "dest": r"E:\a05c\s\managed_components",
    },
    {
        "id": "sdkconfig",
        "kind": "external-file-installed",
        "origin": r"E:\workbuddy\claw4-idf-cold-c5-20260906-frozen-20260912\sdkconfig",
        "version": "frozen C5 configuration",
        "used_as": "SDKCONFIG (explicit)",
        "dest": r"E:\a05c\s\sdkconfig",
    },
    {
        "id": "isolated_src",
        "kind": "replayed-tree",
        "origin": r"E:\a05c\s",
        "version": ("pin ca3aa3fa + A01 + 2c8f58f learning sync (CP2-SOURCE-FIX-001) "
                    "+ A05 patch + frozen sdkconfig; SHORT PATH relocation "
                    "(follow-up A, 2026-09-15) -- same content, digest unchanged"),
        "used_as": "project source (-C)",
        "exclude_dirs": ["managed_components", "build"],
        # CP2-SOURCE-FIX-001 part B: only these three EXACT paths may be excluded
        # from the digest, because ESP-IDF regenerates them inside the source
        # tree during every build. Directory-level exclusion is forbidden.
        "exclude_files": [
            "main/assets/lang_config.h",
            "main/i18n/i18n_strings_gen.h",
            "main/mmap_generate_resources.h",
        ],
    },
]


def measure(entry):
    """Return the measured identity of an entry (origin + installed dest)."""
    out = {"id": entry["id"], "kind": entry["kind"], "origin": entry["origin"],
           "version": entry.get("version", ""), "used_as": entry.get("used_as", "")}
    if entry.get("exclude_dirs"):
        out["exclude_dirs"] = entry["exclude_dirs"]
    exclude_files = list(entry.get("exclude_files", ()))
    if exclude_files:
        out["exclude_files"] = exclude_files
        out["exclude_files_policy"] = ("exact relative file paths only; directory-level "
                                       "exclusion is forbidden; recorded but NOT compared "
                                       "(these files are regenerated by every build)")

    kind = entry["kind"]
    if kind.endswith("-file-installed") or kind == "external-file":
        p = entry.get("dest") or entry["origin"]
        if not os.path.isfile(p):
            out["error"] = "file not found: %s" % p
            return out
        out["origin_sha256"] = sha256_file(entry["origin"]) if os.path.isfile(entry["origin"]) else None
        out["dest"] = entry.get("dest", "")
        out["dest_sha256"] = sha256_file(p)
        out["bytes"] = os.path.getsize(p)
        return out

    root = entry.get("dest") or entry["origin"]
    if not os.path.isdir(root):
        out["error"] = "directory not found: %s" % root
        return out

    problems = validate_exclude_files(entry["id"], exclude_files)
    for p in exclude_files:
        for base in set([entry["origin"]] + ([entry["dest"]] if entry.get("dest") else [])):
            if os.path.isdir(os.path.join(base, p.replace("/", os.sep))):
                problems.append("%s: exclude_files names a directory (not allowed): %r" % (entry["id"], p))
    if problems:
        out["error"] = "; ".join(sorted(set(problems)))
        return out

    digest, count, total, unreadable, ex_state = tree_hash(
        entry["origin"], entry.get("exclude_dirs", ()), exclude_files)
    out["origin_tree_sha256"] = digest
    out["origin_file_count"] = count
    out["origin_bytes"] = total
    if exclude_files:
        out["exclude_file_state"] = ex_state
    if unreadable:
        out["unreadable_or_symlink"] = unreadable
        out["unreadable_count"] = len(unreadable)
    if entry.get("dest"):
        d2, c2, t2, u2, _ex2 = tree_hash(entry["dest"], entry.get("exclude_dirs", ()), exclude_files)
        out["dest"] = entry["dest"]
        out["dest_tree_sha256"] = d2
        out["dest_file_count"] = c2
        out["dest_bytes"] = t2
        if u2:
            out["dest_unreadable_or_symlink"] = u2
    return out


def report_excluded(results):
    """Print, for every entry with excluded generated paths, their current state.

    These values are RECORDED but never compared: the build regenerates them.
    Call this before and after a build to capture the pre/post evidence
    (CP2-SOURCE-FIX-001 part B).
    """
    hit = [r for r in results if r.get("exclude_file_state")]
    if not hit:
        return
    print("")
    print("-- generated paths excluded from the tree digest (state now; NOT compared) --")
    for r in hit:
        print("  %s  (%d path(s))" % (r["id"], len(r["exclude_file_state"])))
        for e in r["exclude_file_state"]:
            if e.get("exists"):
                print("    %-46s exists=True   bytes=%-9s sha256=%s"
                      % (e["path"], e.get("bytes"), e.get("sha256") or e.get("marker")))
            else:
                print("    %-46s exists=False  (not present)" % e["path"])
    print("")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--only", help="restrict to one entry id")
    args = ap.parse_args()
    if args.write == args.check:
        ap.error("give exactly one of --write / --check")

    entries = [e for e in INPUTS if (args.only is None or e["id"] == args.only)]
    results = []
    for e in entries:
        print("hashing %s ..." % e["id"], flush=True)
        results.append(measure(e))

    if args.write:
        doc = {
            "purpose": "A05 build inputs: repo-external inputs frozen by hash; re-verify before each build",
            "tree_hash_definition": 'sha256("\\n".join("<sha256>  <relpath>" sorted by relpath))',
            "policy_ref": "WB-A05-BUILD-001 §3 (input manifest) and reviewer ruling #1",
            "entries": results,
        }
        with open(args.manifest, "w", encoding="utf-8", newline="\n") as f:
            json.dump(doc, f, indent=2, ensure_ascii=False)
            f.write("\n")
        bad = [r for r in results if r.get("error")]
        for r in results:
            print("  %-20s %s" % (r["id"], r.get("error") or
                                  (r.get("dest_tree_sha256") or r.get("dest_sha256") or r.get("origin_tree_sha256"))[:24] + ".."))
        report_excluded(results)
        print("manifest written: %s" % args.manifest)
        return 1 if bad else 0

    if not os.path.isfile(args.manifest):
        print("FAIL: manifest not found: %s" % args.manifest)
        return 1
    old = {e["id"]: e for e in json.load(open(args.manifest, encoding="utf-8"))["entries"]}

    failures = []
    for cur in results:
        ref = old.get(cur["id"])
        if ref is None:
            failures.append("%s: not present in manifest" % cur["id"])
            continue
        if cur.get("error"):
            failures.append("%s: %s" % (cur["id"], cur["error"]))
            continue
        for key in ("origin_tree_sha256", "origin_file_count", "origin_bytes",
                    "origin_sha256", "dest_tree_sha256", "dest_sha256", "bytes",
                    "exclude_dirs", "exclude_files"):
            if key in ref and ref[key] != cur.get(key):
                failures.append("%s: %s changed  manifest=%s  now=%s"
                                % (cur["id"], key, ref[key], cur.get(key)))
        if ref.get("dest") and not cur.get("dest"):
            failures.append("%s: install destination missing" % cur["id"])

    report_excluded(results)
    print("")
    print("manifest : %s" % args.manifest)
    print("entries  : %d checked" % len(results))
    print("failures : %d" % len(failures))
    for f in failures:
        print("  FAIL %s" % f)
    if failures:
        print("RESULT: FAIL -- do NOT build; fix or re-freeze the inputs first")
        return 1
    print("RESULT: PASS -- every external input matches the frozen manifest")
    return 0


if __name__ == "__main__":
    sys.exit(main())
